### ISSUE TITLE
Integration Test Cases for Schema Creation

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#15]
Add more integration test cases for schema creation.

### References

src/k2/dto/ControlPlaneOracle.h (Schema and schema create request definitions)
test/cpo/CPOTest.cpp (existing schema creation tests)

### Happy path test cases

| Test case | Expected Result |
| --- | --- |
| Create a new version of an existing schema by renaming a (non-key) field | 2xx success code, schema can be retrieved through GetSchemasRequest from CPO |
| Create a new version of an existing schema by adding a new field | 2xx success code, schema can be retrieved through GetSchemasRequest from CPO |
| Create a schema which does not have any range key fields set |  2xx success code, schema can be retrieved through GetSchemasRequest from CPO |

### Error test cases

| Test case | Expected Result |
| --- | --- |
| Create a schema with duplicate field names | 400 error code, schema does not exist in result set from GetSchemasRequest |
| Create a schema by setting partitionKeyFields manually by index, and an index is out of bounds of the fields | 400 error code, schema does not exist in result set from Get Schemas Request |
| Create a schema where the field at index 0 is not a partition or range key field | 400 error code, schema does not exist in result set from GetSchemasRequest |
| Create a new version of an existing schema where a key field is renamed | 409 error code, schema does not exist in result set from GetSchemasRequest |
| Create a new version of an existing schema where the type of a key field changes | 409 error code, schema does not exist in result set from GetSchemasRequest |
| Create a new version of an existing schema where a key field is removed | 409 error code, schema does not exist in result set from GetSchemasRequest |

**Comment by YazhiFeng** [comment]
The test cases of this issue are implemented in the following Zip. Including a source file .cpp, a CMakelist.txt and a script .sh. 
[schema_creation_test.zip](https://github.com/futurewei-cloud/chogori-platform/files/5095281/schema_creation_test.zip)

**Comment by jfunston** [comment]
Hi Yazhi, thanks for the test cases, they look great. Can you create a fork of the project on github and submit a pull request that way? Thanks, Justin

**Comment by jfunston** [comment]
Hi Yazhi, thanks again for the pull request. I will merge it and fix the remaining SKVRecord problems. You can begin working on this issue: https://github.com/futurewei-cloud/chogori-platform/issues/22
