### ISSUE TITLE
Support Null in filter expressions

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#168]

**Comment by jfunston** [comment]
In a Query filter expression, the user should be able to specify Null as a literal (e.g. field is < NULL, == NULL, etc). This will require changes to the Query API to specify the NULL literal and changes to the server handling of queries to process it.

**Comment by ahsank** [comment]
@jfunston It seems already handles NULL expression

https://github.com/futurewei-cloud/chogori-platform/blob/master/src/k2/dto/Expression.cpp#L271

With corresponding unit test

https://github.com/futurewei-cloud/chogori-platform/blob/master/test/k23si/ExpressionTest.cpp#L325

**Comment by jfunston** [comment]
ok, thanks, we must have forgotten to close this issue.
