### ISSUE TITLE
cpo client doesn't work in TxnManager during running the K23SITest?

### ISSUE THREAD

**Issue by zsStrike** [futurewei-cloud/chogori-platform#180]
I'm implementing the write async optimization in which trh will track all of the write keys and send response to client without waiting until the persistence job is done. Before the finalization step, trh has to change all write keys to writeRanges. I have used the following method to  accomplish that:

```cpp
K2LOG_D(log::skvsvr, "size: {}", _cpo.collections.size());
for (auto& [cname, infos] : rec.writeInfos) {
    for (auto& info : infos) {
        if (auto it = _cpo.collections.find(cname); it != _cpo.collections.end()) {
            auto& krv = it->second->getPartitionForKey(info.first).partition->keyRangeV;
            rec.writeRanges[cname].insert(krv);
        }
        else {
            K2LOG_W(log::skvsvr, "collection {} does not exist for the write key {}", cname, info.first);
        }
    }
}
```

However, it doesn't work when I run the k23si test. The log shows that the `_cpo.collections.size()` is equal  to `0`, which means that the `collections` is empty. 

The basic solution to solve the problem is to call `_getPartitionGetterForCollection` method using the `_cpo`, but it will involve a lot of network RTT.

So, is there any better solution to work out the problem?

**Comment by jerryhfeng** [comment]
Could you check when and how _cpo.collections is populated? And why it is not populated in your case inside TxnManager?

**Comment by iafuture** [comment]
This is expected. The collections map in the _cpo is lazily populated when you attempt to send. So unless you send via the cpo client (i.e. use the PartitionRequest), there won't be any collections in this map.

**Comment by zsStrike** [comment]
I see now, and I'm going to add writeRange to K23SIWriteKeyRequest struct so that to get around this. Thanks a lot!
