### ISSUE TITLE
Cannot run tpcc benchmark when there are multiple nodepools and tpcc clients

### ISSUE THREAD

**Issue by zsStrike** [futurewei-cloud/chogori-platform#187]
I am going to test the performance of the optimized k23si schma I have implemented. To make the result convincing, I have changed the `test_k23si_tpcc.sh`:

```
EPS="tcp+k2rpc://0.0.0.0:10000 tcp+k2rpc://0.0.0.0:10001 tcp+k2rpc://0.0.0.0:10002 tcp+k2rpc://0.0.0.0:10003"

# start nodepool on 4 cores
./build/src/k2/cmd/nodepool/nodepool -c4 --tcp_endpoints ${EPS} --k23si_persistence_endpoint ${PERSISTENCE} ${COMMON_ARGS} --prometheus_port 63001 --k23si_cpo_endpoint ${CPO} --tso_endpoint ${TSO} --memory=12G --partition_request_timeout=6s &

./build/src/k2/cmd/tpcc/tpcc_client -c4 --tcp_remotes ${EPS} --cpo ${CPO} --tso_endpoint ${TSO} --num_warehouses ${NUMWH} --districts_per_warehouse ${NUMDIST} --prometheus_port 63101 ${COMMON_ARGS} --memory=2G --partition_request_timeout=1s  --num_concurrent_txns=1 --do_verification false --delivery_txn_batch_size=10
```

It allows to run 4 nodepools and 4 tpcc_clients. And when I run the shell scipt, the benchmark cannot go well. The log file is attached here.
[test_k23si_tpcc.log](https://github.com/futurewei-cloud/chogori-platform/files/6673977/test_k23si_tpcc.log)

It seems that there are two transactions having conflict. When some one transaction is pushed to aborted, the twim state is actually InprogressPIP, which not allows the action onAbort. I have tried to ignore the message by allowing onAbort action in InprogressPIP, but there are other problems which may lead to fail exit.

Perhaps we should review the transistion of twim state. By the way, the commit id of the code I run and test is 90133f1 and the branch is futurewei-cloud/chogori-platform/master.

**Comment by iafuture** [comment]
fixed
