### ISSUE TITLE
Add a core-to-core communication method for the applet running in the same process

### ISSUE THREAD

**Issue by piggesthjy** [futurewei-cloud/chogori-platform#2]
I implemented a core-to-core communication method for the applet running in the same process in order to speed up the RPC speed in the same machine. To test it, I merged the txbench_client.cpp and txbench_server.cpp into a single file: txbench_combine.cpp so that the server and the client can run in the same process.

However, when I tested it, it always returned the segmentation fault. When I try to fix this problem, I found this issue is from this function: https://github.com/futurewei-cloud/chogori-platform/blob/master/src/k2/transport/RPCDispatcher.cpp#L118-L151 

Here is the way to reproduce the segmentation fault. Run txbench_combine with args: `./txbench_combine -c 2 --tcp_endpoints 12345 12346 --tcp_remotes tcp+k2rpc://0.0.0.0:12345 --memory 10G  --poll-mode --cpuset 9-10`, it will return a segmentation fault. If I changed the args `--tcp_remotes tcp+k2rpc://0.0.0.0:12345` to `--tcp_remotes tcp+k2rpc://0.0.0.0:12346`, then the benchmark script works well. The only difference between the args is the first args asks the client to communicate with the server that is in the same core, so it will trigger a loop of send/receive requests, which will be processed by _handleNewMessage function.

**Comment by jfunston** [comment]
Resolved
