### ISSUE TITLE
On write precondition failed, heartbeat is not started

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#212]

**Comment by ahsank** [comment]
@jfunston  Is the fix is to start timer when either status is OK or ConditionFailed() in the following code?

https://github.com/futurewei-cloud/chogori-platform/blob/master/src/k2/module/k23si/client/k23si_client.h#L313

Also what is the benefit of starting heartbeat timer if precondition fails?

**Comment by jfunston** [comment]
Yes that is correct. A condition failed code is not a hard error, the client is free to continue its transaction and eventually commit. The way it currently works is that the TRH is created on the nodepool of the first attempted write, regardless if that write failed or not. The TRH is what tracks the transaction heartbeat so we need to start it even if no write intent was created.
