### ISSUE TITLE
Grafana dashboards

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#217]
### Nodepool
- All nodepool specific metrics (those added for issue #211), per shard values without aggregation (except for latencies which can be aggregated for simplicity)
- Aggregate (sum) values for commit txn, read, write, query, abort, and push rates
- From seastar metrics: free memory, RDMA metrics, and reactor busy (these should be on our existing dashboards but may need cleaned up)
- From Node exporter metrics: free and used hugepages if we can get it.

**Comment by ammuv** [comment]
done.
