### ISSUE TITLE
3SI Transaction Test cases scenarios 00 and 01

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#22]
Implement integration tests described in https://github.com/futurewei-cloud/chogori-platform/blob/master/docs/RFC/K23SI_testing.md

Each scenario set described in the RFC can be a separate pull request.

**Comment by YazhiFeng** [comment]
When implementing **Scenario 01**, I encounter the following couple problems:

problem 1.    In cases 1, 3, 4, 5 which expect result of "RefreshCollection", FINALIZE operation does not return “Collection Refresh needed” result.  Then i check function handleTxnFinalize() in Module.cpp, finding that “_validateRequestPartition（req）” is not included. Thus should FINALIZE operations not be included in the test case？

problem 2.    In case 2 which expects result of “request too old”, only  READ, WRITE, END, HEARTBEAT operations perform timestamp stale detection. Other functions corresponding to the verbs are not able to return a "request too old" message. Thus should only  READ, WRITE, END, HEARTBEAT operations  be included in this test case 2？

**Comment by iafuture** [comment]
On problem 1:
This is indeed a problem. handleTxnFinalize() needs to be partition-aware, and as such it is possible to attempt to finalize a record in a partition which has been moved. The receiver should use _validateRequestPartition to make sure. You should be getting RefreshCollection response in this case and FINALIZE should be included in the test case

On problem 2:
The question is about PUSH and FINALIZE when the operation is outside retention window.
- PUSH needs to check if the request is still inside the retention window. There shouldn't be a scenario in which a PUSH operation outside the retention window is still valid so PUSH needs to be included in this test case. 
- FINALIZE could technically occur outside the retention window - we can accept a Commit from a client while still in the window, but by the time we get to finalize things, we may be outside the window. FINALIZE should therefore be excluded from this test case. In fact, we should have a test case to make sure we can FINALIZE outside of the retention window.

**Comment by jfunston** [comment]
Hi Yazhi, can you implement the fixes Ivan mentioned as part of your PR? Let us know if there is any other problem.

**Comment by YazhiFeng** [comment]
Both the fixes in the test cases Table and Ivan mentioned are implemented in the pull request. 

I got a **question** while implementing test case "FINALIZE outside of the retention window" :
I use the following set of operations to get a staled MTR, but not sure whether is correct or not :

1. when creating the collection,  set the .retentionPeriod to 500ms ;
2. get a Timestamp and use it to form MTR, then use the MTR to doWrite;
3. sleep for 5 seconds;
4. Finalize the write intent using the former MTR.
5. start another txn and doRead to valid .

**Comment by iafuture** [comment]
I wouldn't sleep for that long as it adds to the test total run time. you can sleep for 500ms. I'm not sure how your change looks like, but for this to work, you'll have to expose the "retention_minimum" configuration as a command-line argument and set it to 500ms as well. Otherwise the cluster will reset your 500ms to 1hr.

The above is a full integration test and it's good. You should also  test the FINALIZE call separately by issuing a FINALIZE for a key outside of a transaction and outside the retention window.  Test both finalize for ABORT and finalize for COMMIT.
In Abort-finalize, you should get a dto::K23SIStatus::OK. In Commit-finalize, you should get a dto::K23SIStatus::OperationNotAllowed

**Comment by YazhiFeng** [comment]
As you said, i find what I do is wrong, without exposing the "retention_minimum" configuration, I am not able to set the retention window to less than 1hr. 

So i  test the FINALIZE call separately in the Scenario 01 test by using an old enough timestamp. I can get response dto::K23SIStatus::OK in Abort-finalize and dto::K23SIStatus::OperationNotAllowed in Commit-finalize. This test case is in Scenario-01, case-02. Please check it.

Other comments are also met in Scenario-01 cases in the PR#34.

**Comment by jfunston** [comment]
I merged the PR. I will close this issue and create new ones for the other scenarios. Thanks again!
