### ISSUE TITLE
Improve testing for HTTP proxy client

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#270]
The HTTP proxy client receives requests from HTTP in JSON format and forwards the requests through the native C++ chogori client. Currently it only supports a static collection and schemas with begin txn, read, write, and end txn support. First we should improve the testing of the existing functionality.

- Python test script: test/integration/test_http.py
- Runner test script: test/integration/test_http_client.sh
- HTTP proxy client implementation: src/k2/cmd/httpclient/http_client.cpp
- C++ native client implementation: src/k2/module/k23si/client/k23si_client.h

Tests to add:
- Read/Write/End with a bad txn id.
- Read/write with a bad schemaName
- Write with a bad schemaVersion
- Read a non-existent key
- Using two txns, a write-after-read conflict
- Read/write with a field specified that is not part of the schema
- Read/write with a field where the value type does not match the schema

**Comment by ahsank** [comment]
@jfunston The issue is fixed.
