### ISSUE TITLE
Support binary json format in HTTP Proxy

### ISSUE THREAD

**Issue by ahsank** [futurewei-cloud/chogori-platform#283]
Based on testing done by @iafuture , some binary json format more efficient than text json

Testing with canada.json
    size=2090303bytes
    json    /dump:  13418.3 us per op
    json    /load:  37862.5 us per op
    bson    /dump:  80577.1 us per op
    bson    /load:  21250.7 us per op
    msgpack /dump:  2379.73 us per op
    msgpack /load:  18262.1 us per op
    cbor    /dump:  2381.4 us per op
    cbor    /load:  18406.3 us per op
    ubjson  /dump:  2570.28 us per op
    ubjson  /load:  18508.7 us per op
took 50 iterations
Testing with twitter.json
    size=466906bytes
    json    /dump:  2707.18 us per op
    json    /load:  5527.61 us per op
    bson    /dump:  1966.88 us per op
    bson    /load:  5341.61 us per op
    msgpack /dump:  1578.61 us per op
    msgpack /load:  5247.47 us per op
    cbor    /dump:  1619.2 us per op
    cbor    /load:  5286.3 us per op
    ubjson  /dump:  967.438 us per op
    ubjson  /load:  6691.41 us per op
took 126 iterations
Testing with citm_catalog.json
    size=500299bytes
    json    /dump:  2560.69 us per op
    json    /load:  7500.18 us per op
    bson    /dump:  7474.82 us per op
    bson    /load:  7731.32 us per op
    msgpack /dump:  1945.86 us per op
    msgpack /load:  7639.5 us per op
    cbor    /dump:  2016.49 us per op
    cbor    /load:  8535.52 us per op
    ubjson  /dump:  1120.66 us per op
    ubjson  /load:  8841.97 us per op
took 132 iterations
Testing with simple object
    size=719bytes
    json    /dump:  4.384 us per op
    json    /load:  8.353 us per op
    bson    /dump:  2.12 us per op
    bson    /load:  5.667 us per op
    msgpack /dump:  2.34 us per op
    msgpack /load:  5.661 us per op
    cbor    /dump:  2.502 us per op
    cbor    /load:  5.035 us per op
    ubjson  /dump:  1.974 us per op
    ubjson  /load:  6.711 us per op
took 76076 iterations
root@2898d24951c9:/build/jstest#

**Comment by jfunston** [comment]
Using msgpack now instead of json
