### ISSUE TITLE
Fixes for minimum transaction time

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#295]
Currently the minimum transaction time is statically coded to 50us in the k23si client.

- TSO should report max error bound to CPO
- CPO should report max error bound among all TSOs to k23si client
- k23si client should use this error bound as the minimum transaction time
- minimum transaction time needs to be implemented for read only transactions as well
- Run YCSB benchmarks, we should see an improvement to the write heavy workloads

**Comment by ahsank** [comment]
@jfunston How TSO knows its error bound to report to CPO? Will CPO get all TSO clock values and compare with CPO clock to find relative drift? Let if know if the process is described in anywhere.

**Comment by jfunston** [comment]
I think to simplify for now, let's skip the steps for getting the error bounds and aggregating from the TSOs. So instead let's add a new configuration variable to the CPO for the minimum transaction time with a default of 20us. This value still needs to be communicated to the client. I think the TSO client should be the component to get it from the CPO as part of its bootstrap ( https://github.com/futurewei-cloud/chogori-platform/blob/master/src/k2/tso/client/Client.cpp#L62 ). Then the K23SI client should get it from the TSO client.

**Comment by ahsank** [comment]
@jfunston  Few questions

1. Is the error bound value same for all TSOs or TSO services or can be different?
2. I don't see TSO calling CPO at startup, should it also call CPO to get this config?
