### ISSUE TITLE
3SI transaction test cases scenario 4

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#40]
Implement tests from scenario 4 from here: https://github.com/futurewei-cloud/chogori-platform/blob/master/docs/RFC/K23SI_testing.md

You can come up with the test cases and expected result, and add to the testing documentation above.

**Comment by YazhiFeng** [comment]
I wanna ask how to make the time beyond the retention window when implementing scenario 08 ?

**Comment by jfunston** [comment]
I think you can skip that part of scenario 08 for now. We don't want the test itself to be timing dependent or rely on a long sleep, and I don't think we have a better way to do it right now.

**Comment by jfunston** [comment]
Hi Yazhi, thanks again for your work on the tests. I had a couple more comments on scenario 08 and then it should be ready to go. Next, you can work on these issues:
https://github.com/futurewei-cloud/chogori-platform/issues/44
https://github.com/futurewei-cloud/chogori-platform/issues/1
