### ISSUE TITLE
Implement projection for Query

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#58]

**Comment by jfunston** [comment]
For the SKV Query operation (a read-only range scan) we want to support projection, meaning that user specifies which fields of each record they want. This is used to optimize data transfer by letting the user tell us which fields they need. The user will specify the fields for project by name only. The client-side interface for this is already defined but not implemented: src/k2/module/k23si/client/query.h

The DTO interface is also already defined in K23SIQueryRequest. The server-side needs to be implemented. The user will get SKVRecords back as the result. If a field is not part of the user projection, then it is indicated by the excludedFields value in the SKVRecord and is not part of the fieldData payload. It is up to the user to know which fields they asked to be projected so they know how to interpret an SKVRecord. If the user did not call addProjection then it should be assumed they want all fields. If a record on the server would be returned to the user but it does not have a field named by the projection, then we take the flexible approach and return that record to the user but without that field (in other words, projection never affects which records are returned to the user).

**Comment by YazhiFeng** [comment]
I've read interface of SKV query and related functions. Whether the projection needs to be integrated within the query request or as a separate request？

**Comment by jfunston** [comment]
Projection should be integrated as part of the query request.

**Comment by jfunston** [comment]
You can start on https://github.com/futurewei-cloud/chogori-platform/issues/59 next. As always feel free to ask me questions on the issue or in the open source meeting.
