### ISSUE TITLE
Add skip and copy methods to Payload

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#74]
This would reduce data copies in the code that needs this functionality (e.g. in partial update code in Module.cpp)

**Comment by jerryhfeng** [comment]
Curious if the compiler could optimize it away. But even so, it still worth to make the code change for better readability/intention.

**Comment by iafuture** [comment]
it'd be nice to have an api on Payload to help copy raw data from one payload to another (e.g. during projection)
Proposed api:
``` c++
template <typenameT>
bool copy<T>(Payload& dst);
```
