### ISSUE TITLE
Implement Order Status TPC-C Transaction

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#78]
See section 2.6 in the spec: http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-c_v5.11.0.pdf

If the spec mentions any terminal display or file output, we do not want to do that but the data needed for it should be retrieved from SKV and stored in the transaction context. For example, in the New Order transaction in src/k2/cmd/tpcc/transactions.h the tax, discount, and total_amount variables are saved as member variables but are not used in the code.

**Comment by YazhiFeng** [comment]
Hi, Justin. The Order Status is almost done. But I got a problem that I don't know how to use an Expression Filter to filter out a particular string. For example, makeValueReference("LastName") is used to indicate a field and makeValueLiteral<k2::String>("lastNameStr") is used to denote a string. When making expression with operation EQ, no record would be found. While making expression with operation STARTS_WITH or else, we could find the record. So how to filter a string A that equals to string B?

**Comment by jfunston** [comment]
Hi Yazhi, thanks for pointing this out. It should be fixed now. You will need to pull and rebuild the chogori-seastar-rd dependency.

**Comment by jfunston** [comment]
Hi Yazhi, you can also start thinking about what you want to work on next after you finish the three transactions. Let us know what you are interested in and we can discuss more. Some ideas:

- performance profiling (function profiling and metrics)
- improve testing infrastructure (e.g. failure injection)
- improve logging (more dynamic, maybe logstash integration)
- make configuration dynamic
- support read-only read committed isolation transactions (see docs/RFC/K23SI-ReadCommitted.md)
- Finish implementing the TPC-C verification tests
- Any other idea you have

**Comment by jfunston** [comment]
Completed
