### ISSUE TITLE
Implement Delivery TPC-C Transaction

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#79]
See section 2.7 in the spec: http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-c_v5.11.0.pdf

If the spec mentions any terminal display or file output, we do not want to do that but the data needed for it should be retrieved from SKV and stored in the transaction context. For example, in the New Order transaction in src/k2/cmd/tpcc/transactions.h the tax, discount, and total_amount variables are saved as member variables but are not used in the code.

**Comment by YazhiFeng** [comment]
Hi Justin, I got two questions about Delivery TPC-C transaction:

1. According to the spec, the Delivery Transaction is intended to be executed in defferred mode. I wanna make sure whether it's necessary to delay execution. I think make 10 txns to proces new order will be fine.

2. In the end of Delivery Transaction, a result file will be written. Can I do this by writing KV pairs?

**Comment by jfunston** [comment]
1. I agree we don't need to do deferred mode. I'm not sure if 10 txns would be better than 1, maybe make it configurable. It might also make sense to execute these with lower txn priority.
2. You don't need to write KV pairs or to file. You can save the information in memory on the client like we do for the other transaction types.

**Comment by jfunston** [comment]
Completed
